# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc6dd16dcb01fea37c5d105deda5b1366c68730220437e41d70b36bcb0bc62e65c647908f414c8982bdce7baa09dc924fb9e977cdda97758ddc51e1ded524f30

test:
  secret_key_base: dabaa1ce44a05d1e1bc56681587a991d5e9ae8ed101511a109b4cfa09044bb012a2dd633781533e314659fd740b3c4fa9b00aae40eb38213338fad6f0ebe9ab8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
